version: "3"

services:
  pg:
    build: docker/postgres
    environment:
      - "POSTGRES_DB=${PG_DB_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./docker/data/postgres_volume:/var/lib/postgresql/data
    env_file:
     - .env